---
matrix:
  include:
    - os: osx
      before_install:
        - brew update
        - brew install gnu-tar
        - brew install moreutils
        - brew install shellcheck
      script: make test
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - devscripts
            - debhelper
            - moreutils
            - fakeroot
            - shellcheck
      script: debuild -uc -us
