---
matrix:
  include:
    - os: osx
      before_install:
        - brew update
        - brew install gnu-tar
        - brew install moreutils
        - brew install shellcheck
      script: make test
    - os: linux
      dist: trusty
      sudo: required
      install:
        - wget "https://storage.googleapis.com/shellcheck/shellcheck-stable.linux.x86_64.tar.xz"
        - tar --xz -xvf "shellcheck-stable.linux.x86_64.tar.xz"
        - shellcheck() { "shellcheck-stable/shellcheck" "$@"; }
        - shellcheck --version
      addons:
        apt:
          packages:
            - devscripts
            - debhelper
            - moreutils
            - fakeroot
      script: debuild -uc -us
