---
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - devscripts
            - debhelper
            - moreutils
            - fakeroot
      script: debuild -uc -us
