---
###########################################
# These are the rules used for            #
# linting all the yaml files in the stack #
# NOTE:                                   #
# You can disable line with:              #
# # yamllint disable-line                 #
###########################################
rules:
  braces: disable
    # level: warning
    # min-spaces-inside: 0
    # max-spaces-inside: 0
    # min-spaces-inside-empty: 1
    # max-spaces-inside-empty: 5
  brackets: disable
    # level: warning
    # min-spaces-inside: 0
    # max-spaces-inside: 0
    # min-spaces-inside-empty: 1
    # max-spaces-inside-empty: 5
  colons: disable
    # level: warning
    # max-spaces-before: 0
    # max-spaces-after: 1
  commas: disable
    # level: warning
    # max-spaces-before: 0
    # min-spaces-after: 1
    # max-spaces-after: 1
  comments: disable
  comments-indentation: disable
  document-end: disable
  document-start: disable
  empty-lines: disable
    # level: warning
    # max: 2
    # max-start: 0
    # max-end: 0
  hyphens: disable
    # level: warning
    # max-spaces-after: 1
  indentation: disable
    # level: warning
    # spaces: consistent
    # indent-sequences: true
    # check-multi-line-strings: false
  key-duplicates: enable
  line-length: disable
  new-line-at-end-of-file: disable
  new-lines: diable
    # type: unix
  trailing-spaces: disable