name: Run Integration Tests

on: [pull_request, workflow_dispatch]

# Get target and source branch from different variables depending on how it was triggered
env:
  TARGET_BRANCH: '${{ github.event.inputs.target-branch }}${{ github.base_ref || github.ref_name }}'
  SOURCE_BRANCH: '${{ github.event.inputs.source-branch }}${{ github.head_ref || github.ref_name }}'

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jankyJobName:
        - enterprise2-backup-utils-binary-backup
        - enterprise2-backup-utils-migration
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Queue ${{ matrix.jankyJobName }} build
        run: |
          ref="${{ github.ref }}"
          merge_branch=${ref#"refs/heads/"}
          backup_utils_branch="${{ env.SOURCE_BRANCH }}"
          branch_name="${{ env.TARGET_BRANCH }}"
          curl -v -X POST \
            -u "hubot:${{ secrets.API_AUTH_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"buildable_name":"${{ matrix.jankyJobName }}","repo":"${{ github.repository }}","branch_name": "'"$branch_name"'","env_vars":{"JANKY_ENV_BACKUP_UTILS_BRANCH": "'"$backup_utils_branch"'" },"force":"true","room_id":"#builds"}' \
            "https://janky.githubapp.com/api/builds"
