name: Long Running Nightly Tests
on:
  schedule:
  - cron:  '0 0 * * *'
  workflow_dispatch:

# Get target and source branch from different variables depending on how it was triggered
env:
  TARGET_BRANCH: '${{ github.event.inputs.target-branch || github.base_ref }}'
  SOURCE_BRANCH: '${{ github.event.inputs.source-branch || github.head_ref }}'

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jankyJobName:
        - enterprise2-backup-utils-cluster-binary-backup
        - enterprise2-backup-utils-cluster-migration
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Queue ${{ matrix.jankyJobName }} build
        uses: ./.github/actions/proxy-janky-build
        id: proxy-janky-build
        with:
          janky-token: '${{ secrets.API_AUTH_TOKEN }}'
          job-name: '${{ matrix.jankyJobName }}'
          branch-name: '${{ github.ref_name  }}'
          force : "true"
          # enterprise2 target branch is same as target branch for PR (either master or enterprise-[0-9]*.[0-9]*-release)
          envVars: "JANKY_ENV_BACKUP_UTILS_BRANCH=${{ github.ref_name }},JANKY_ENV_ENTERPRISE2_BRANCH=${{ github.ref_name }}"
