name: Restore Dataset
run-name: ${{ github.actor }} retrieving data-sets 
on:
  workflow_dispatch:
    inputs:
      size:
        description: 'Size of the dataset to restore'
        required: true
        type: choice
        options:
        - 'small'
        - 'medium'
      hostname:
        description: 'Hostname of the server'
        required: true
        type: string
      ref:
        description: 'Branch ref to use'
        required: false
        type: string
        default: 'master'
      version: 
        description: 'GHES Version of dataset'
        required: false
        type: string
        default: "3.8.0"
  workflow_call:
    inputs:
      size:
        description: 'Size of the dataset to restore'
        required: false
        type: string
        default: 'small'
      hostname:
        description: 'Hostname of the server'
        required: true
        type: string
      ref:
        description: 'Branch ref to use'
        required: false
        type: string
        default: 'master'
      version: 
        description: 'GHES Version of dataset'
        required: false
        type: string
        default: "3.8.0"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: github/backup-utils-private
        ref: ${{ inputs.ref }}
    - run: docker build . --file Dockerfile --tag backup-utils 
    - run: docker save backup-utils -o backup-utils.tar
    - uses: actions/upload-artifact@v3
      with:
        name: backup-utils
        path: backup-utils.tar
  restore:
    needs: build
    runs-on: ubuntu-latest
    env:
        SSH_KEY: ${{ secrets.BACKUP_SSH_KEY }}
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: backup-utils
    - name: Load docker container 
      run: docker load -i backup-utils.tar
    - uses: actions/checkout@v3
      with:
        repository: github/ghes-data
        ref: main
    - run: tar zxvf ghes-data/data/backup/${{ inputs.size }}/v3.8.0/${{ inputs.size }}-refined.tar.gz
    - run: ls -al ghes-data/data/backup/${{ inputs.size }}




